# https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions
name: npm Package CI
description: Simple CI for your npm packages.
author: Daniel Bayley
branding:
  icon: package
  color: red

inputs:
  node-version:
    description: Node.js version, or versions in CSV format.
    required: true

  test-reporter:
    description: Specify a node --test-reporter.

  todo-annotate:
    description: Annotate tests marked .todo.

  todo-fail-warn:
    description: Show failed tests marked .todo as warnings.

outputs:
  package-manager:
    description: Detected package manager.
    value: ${{ steps.js.outputs.package-manager }}

  package-file:
    description: Detected package.* file.
    value: ${{ steps.js.outputs.package-file }}

  options:
    description: NODE_OPTIONS
    value: ${{ steps.js.outputs.options }}

  test:
    description: The scripts.test command.
    value: ${{ steps.js.outputs.test }}

runs:
  using: composite
  steps:
  - id: metadata
    uses: ./metadata

  - shell: sh
    run: echo '${{ steps.metadata.outputs.keywords }}'
