# https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions
$schema: https://json.schemastore.org/github-workflow
name: npm Package CI
description: Easy CI for your npm packages.
author: Daniel Bayley
branding:
  icon: package
  color: red

inputs:
  node-version:
    description: Node.js version, or versions in CSV format.
    required: true

  test-reporter:
    description: Specify a node --test-reporter.

  todo-annotate:
    description: Annotate tests marked .todo.

  todo-fail-warn:
    description: Show failed tests marked .todo as warnings.

outputs:
  package-manager:
    description: Detected package manager.
    value: ${{ steps.node.outputs.package-manager }}

  options:
    description: NODE_OPTIONS
    value: ${{ steps.node.outputs.options }}

  test:
    description: The scripts.test command.
    value: ${{ steps.node.outputs.test }}

runs:
  using: composite
  steps:
  - uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}

  - shell: sh
    run: npm install --global --force corepack && corepack enable

  - id: node
    working-directory: ${{ github.action_path }}
    shell: sh
    run: pnpm install
    env:
      INPUT_REPORTER: ${{ inputs.test-reporter }}

  - if: inputs.test-reporter
    shell: sh
    run: ${{ steps.node.outputs.add }}

  - uses: actions/setup-node@v4
    with:
      cache: ${{ steps.node.outputs.package-manager }}

  - shell: sh
    run: ${{ steps.node.outputs.install }}
