# https://docs.npmjs.com/cli/configuring-npm/package-json
$schema: https://json.schemastore.org/package
name: &name npm-package-ci
description: Simple CI for your npm packages.
keywords:
- ci
- test
- github
- actions
- reporter

homepage: https://github.com/danielbayley/npm-package-ci#readme
repository: danielbayley/npm-package-ci
bugs: https://github.com/danielbayley/npm-package-ci/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: danielbayley.dev

license: MIT
funding: https://github.com/sponsors/danielbayley

private: true
type: module
exports: ./index.js

engines:
  node: ">=20"
  pnpm: ">=10"
packageManager: pnpm@10.2.0
pnpm:
  requiredScripts: [test]
  onlyBuiltDependencies:
  - *name
  - node--test-parser
  - node--test-reporter-github
  - utils

dependencies:
  node-test-reporter-github: workspace:*
  utils: workspace:*

devDependencies:
  jsdom: &catalog catalog:default
  yaml:  *catalog

scripts:
  pnpm:devPreinstall: yq --output-format json package.yaml > package.json
  postinstall: node index.js >> $GITHUB_OUTPUT
  test: pnpm --stream --reporter-hide-prefix --recursive test
