# https://docs.npmjs.com/cli/configuring-npm/package-json
$schema: https://json.schemastore.org/package
version: 0.0.0
name: "@danielbayley/node-test-parser"
description: Parse events from node --test into a more useable data structure.
keywords:
- test
- events
- emit
- reporter
- coverage
- data

homepage: https://github.com/danielbayley/npm-package-ci/tree/main/packages/node-test-parser#readme
repository: danielbayley/npm-package-ci
bugs: https://github.com/danielbayley/npm-package-ci/tree/main/packages/node-test-parser/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: danielbayley.dev

license: MIT
funding: https://github.com/sponsors/danielbayley

type: module
imports:
  "#index": &index ./index.js
  "#events": ./test/fixtures/events.json
exports: *index
files: [*index]
directories: &directories
  fixtures: ./test/fixtures

engines:
  node: ">=20"
  pnpm: ">=10"
packageManager: pnpm@10.2.1

devDependencies:
  yaml: catalog:default

config: *directories
scripts:
  prepare: yaml --single --json --indent ${TABSIZE:-2} < package.yaml > package.json

  test: node --experimental-test-coverage --test test/unit.js
  pretest: >-
    NODE_OPTIONS= node
    --test-reporter $npm_package_config_fixtures/generate.js
    --test-reporter-destination $npm_package_config_fixtures/events.json
    --experimental-test-coverage
    --test $npm_package_config_fixtures/tests.js || true

  version: |
    sed -i "" -E "s/^(version: *)$npm_old_version\$/\\1$npm_new_version/" package.yaml
    git commit --all --message $npm_package_version
  postversion: |
    git tag --annotate v$npm_package_version -m ""
    git push --follow-tags

  prerelease: git stash --all --include-untracked --keep-index --quiet
  release: pnpm test && pnpm version
  postrelease: pnpm publish && git stash pop --index --quiet
