# https://docs.npmjs.com/cli/configuring-npm/package-json
$schema: https://json.schemastore.org/package
version: 0.0.0
name: "@danielbayley/node-test-parser"
description: Parse events from node --test into a more useable data structure.
keywords:
- test
- events
- emit
- reporter
- coverage
- data

homepage: https://github.com/danielbayley/npm-package-ci/tree/main/packages/node--test-parser#readme
repository: danielbayley/npm-package-ci
bugs: https://github.com/danielbayley/npm-package-ci/tree/main/packages/node--test-parser/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: danielbayley.dev

license: MIT
funding: https://github.com/sponsors/danielbayley

type: module
imports:
  "#index": &index ./index.js
  "#events": ./test/fixtures/events.json
exports: *index
directories:
  build: &build build
  fixtures: ./test/fixtures
files: [*index]

engines:
  node: ">=20"
  pnpm: ">=10"
packageManager: pnpm@10.2.0

devDependencies:
  "@danielx/civet": &catalog catalog:default
  replace-in-file:  *catalog
  yaml: *catalog

publishConfig:
  access: public
  directory: *build

scripts:
  prepare: yaml --single --json --indent 2 < package.yaml > package.json
  pretest: >-
    NODE_OPTIONS=
    pnpm prepare &&
    node
    --test-reporter $npm_package_directories_fixtures/generate.js
    --test-reporter-destination $npm_package_imports__events
    --experimental-test-coverage
    --test $npm_package_directories_fixtures/tests.js || true
  test: >-
    node
    --test-reporter spec
    --test-reporter-destination stdout
    --experimental-test-coverage
    --test test/unit.js

  prepublishOnly: |
    mkdir -p $npm_package_publishConfig_directory
    mv package.json $npm_package_publishConfig_directory
    cp $npm_package_files_0 $npm_package_publishConfig_directory

  version: |
    replace-in-file version:\ $npm_{old,new}_version package.yaml
    git commit --all --message $npm_package_version
  postversion: |
    git tag --annotate v$npm_package_version -m ""
    git push --follow-tags

  prerelease: git stash --all --include-untracked --keep-index --quiet
  release: pnpm test && pnpm version
  postrelease: pnpm publish && git stash pop --index --quiet
