# https://docs.npmjs.com/cli/configuring-npm/package-json
version: 0.0.0
name: "@danielbayley/node-test-parser"
description: Parse events from node --test into a more useable data structure.
keywords:
- test
- events
- emit
- reporter
- coverage
- data

homepage: https://github.com/danielbayley/npm-package-ci/tree/main/node-test-parser#readme
repository: danielbayley/npm-package-ci
bugs: https://github.com/danielbayley/npm-package-ci/tree/main/node-test-parser/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: danielbayley.dev

license: MIT
funding: https://github.com/sponsors/danielbayley

type: module
imports:
  "#index": &index ./index.js
  "#events": ./test/fixtures/events.json
exports: *index
files: [*index]
directories: &directories
  fixtures: ./test/fixtures
publishConfig:
  access: public

devDependencies:
  publint: catalog:default
  utils: workspace:^

config: *directories
scripts:
  prepare: node --import utils/scripts/prepare

  test: node --experimental-test-coverage --test test/unit.js
  pretest: >-
    NODE_OPTIONS= node
    --test-reporter $npm_package_config_fixtures/generate.js
    --test-reporter-destination $npm_package_config_fixtures/events.json
    --experimental-test-coverage
    --test $npm_package_config_fixtures/tests.js || true

  release: pnpm version --force --no-git-tag-version
  postrelease: pnpm publish

  prepublishOnly: publint
  version: |
    sed -i "" -E "s/^(version: *)$npm_old_version\$/\\1$npm_new_version/" package.yaml
    git commit --message $npm_new_version package.yaml
  postversion: |
    git tag  --annotate $npm_new_version --message v$npm_new_version
    git push --follow-tags

  watch: pnpm test --watch
  reinstall: pnpm zap && pnpm install
  zap: rm -rf node_modules/
