# https://docs.npmjs.com/cli/configuring-npm/package-json
$schema: https://json.schemastore.org/package
name: utils #&name
keywords:
- library
- utils
- testing

private: true
type: module
imports:
  "#test": &test ./test.js
exports:
  .: ./index.mjs
  ./test: *test
  ./scripts/*: ./scripts/*.*js

engines:
  node: ">=20"
  pnpm: ">=10"
packageManager: pnpm@10.4.1
#pnpm:
  #onlyBuiltDependencies: [*name]

dependencies:
  jsdom: &catalog catalog:default

optionalDependencies: #peerDependencies:
  yaml: *catalog
#peerDependenciesMeta:
  #yaml:
    #optional: true

devDependencies:
  yaml: *catalog

scripts:
  prepare: yaml --single --json --indent ${TABSIZE:-2} < package.yaml > package.json
  test: node --experimental-test-coverage --test test/unit.js
