# https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions
name: CI
on:
  push:
    branches: [main]

  workflow_call:
    inputs:
      node-version:
        description: Node.js version, or versions in CSV format.
        type: string

      test-reporter:
        description: Specify a node --test-reporter.
        type: string
        #default: node--test-reporter-github TODO

      #test-coverage:
        #description: Enable node --experimental-test-coverage.
        #type: boolean
        #default: true

      annotate-todo:
        description: Annotate tests marked .todo.
        type: boolean
        default: true

jobs:
  Node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(format('[{0}]', inputs.node-version || '18, 19, 20, 21, 22')) }}

    env: # https://nodejs.org/api/test.html#test-reporters
      NODE_OPTIONS: --test-reporter=spec --test-reporter-destination=stdout #--experimental-test-coverage FIXME
      INPUT_ANNOTATE_TODO: ${{ inputs.annotate-todo }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js ${{ matrix.node-version }} and dependencies
      id: node
      uses: danielbayley/npm-package-ci@main #v1
      with:
        node-version:  ${{ matrix.node-version  }}
        test-reporter: ${{ inputs.test-reporter }}
        #test-coverage: ${{ inputs.test-coverage }}
        annotate-todo: ${{ inputs.annotate-todo }}

    - name: Run tests
      run: ${{ steps.node.outputs.test }} #${{ inputs.test-coverage }}
      env:
        NODE_OPTIONS: ${{ env.NODE_OPTIONS }} ${{ steps.node.outputs.options }}
