name: Release
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ toJSON(github.event) }}'
